In [12]:
#Full,Ones,Zeros,Eye,Random
import numpy as np

In [13]:
l = [ [1, 12, 0, 4], [13, 2, 10, 5] ]  

In [14]:
arr = np.array(l)


In [15]:
arr


array([[ 1, 12,  0,  4],
       [13,  2, 10,  5]])

In [17]:
#Syntax :- np.full( shape, value )
arr1 = np.full( ( 2, 5 ), 3 )
print( arr )
print()
print( arr1 )
print()
print( type(arr1) )

print( arr.dtype )

[[ 1 12  0  4]
 [13  2 10  5]]

[[3 3 3 3 3]
 [3 3 3 3 3]]

<class 'numpy.ndarray'>
int32


In [8]:
#Syntax :- np.zeros( shape )
arr2 = np.zeros( ( 2, 5 ) )
print( f"arr2 = { arr2 }, type( arr2) = { type( arr2 ) } and arr2.dtype = { arr2.dtype }" )

arr2 = [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]], type( arr2) = <class 'numpy.ndarray'> and arr2.dtype = float64


In [20]:
#Syntax :- np.ones( shape )
arr3 = np.ones( ( 2, 5 ) )
print( f"arr = { arr3 }, type( arr) = { type( arr3 ) } and arr.dtype = { arr3.dtype }" )

arr = [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]], type( arr) = <class 'numpy.ndarray'> and arr.dtype = float64


In [25]:
#Syntax :- np.eye( shape1, shape2 ) #rows,columns
arr4 = np.eye( 5, 5 )
print( f"{ arr4 }, type( arr4) = { type( arr4 ) } and arr4.dtype = { arr4.dtype }" )

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]], type( arr4) = <class 'numpy.ndarray'> and arr4.dtype = float64


In [29]:
#Syntax :- np.random.random( shape )
arrrandom = np.random.random( (2, 4, 3) ) #2 is list, 4 is row and 3 is column
print( arrrandom )
print( arrrandom.dtype )
print( arrrandom.shape )

[[[0.25916923 0.47863745 0.60776524]
  [0.36772634 0.79764138 0.27936959]
  [0.69212171 0.24203159 0.01685712]
  [0.08670678 0.61528669 0.93063299]]

 [[0.09383579 0.28489226 0.11861713]
  [0.67892891 0.64073423 0.42963877]
  [0.28511484 0.77189875 0.97753565]
  [0.77861298 0.39165943 0.6162677 ]]]
float64
(2, 4, 3)


In [21]:
#Syntax :- np.random.randint( start, end, shape )
n1 = np.random.randint( 2, 10, 4 )
n2 = np.random.randint( 12, 20, 4 )
n3 = np.random.randint( 12, 20, ( 2, 5 ) )

print( f"n1 = { n1 }" )
print( f"n2 = { n2 }" )
print( f"n3 = { n3 }" )

n1 = [4 7 3 9]
n2 = [18 15 12 17]
n3 = [[17 12 19 14 13]
 [17 13 16 19 14]]
