In [1]:
#Mean, Median, Sum, exp
import numpy as np

In [8]:
arr1 = np.array( [ list( range(1, 11, 3) ), list( range(11, 21, 3) ), list( range(21, 31, 3) ) ], dtype = np.float64 )
print( arr1 )
print( type( arr1 ) )
print( arr1.dtype )  #To see the data type of all the elements of numpy array

[[ 1.  4.  7. 10.]
 [11. 14. 17. 20.]
 [21. 24. 27. 30.]]
<class 'numpy.ndarray'>
float64


In [6]:
arr2 = np.array( [ [6.2, 5.9, 1.9, 2.2], [8.8, 1.1, 9.6, 2.9], [ 1, 3.45, 5.43, 4.35 ] ], dtype = np.int64 )
print(arr1)
print()
print(arr2)

[[ 1.  4.  7. 10.]
 [11. 14. 17. 20.]
 [21. 24. 27. 30.]]

[[6 5 1 2]
 [8 1 9 2]
 [1 3 5 4]]


In [10]:
#Addition of 2 ndarrays
arrsum = arr1+arr2
print(f"arrsum = {arrsum}, dtype = {arrsum.dtype}" )
arrsum.dtype = np.int64
print(f"dtype = {arrsum.dtype}" )

arrsum = [[ 7.  9.  8. 12.]
 [19. 15. 26. 22.]
 [22. 27. 32. 34.]], dtype = float64
dtype = int64


In [11]:
#Substraction of 2 ndarrays

arrsub = arr1-arr2
print( arrsub )
print( arrsub.dtype )
print( type( arrsub ) )

[[-5. -1.  6.  8.]
 [ 3. 13.  8. 18.]
 [20. 21. 22. 26.]]
float64
<class 'numpy.ndarray'>


In [12]:
#Multition of 2 ndarrays
arrmult = arr1*arr2
print( arrmult )
print( arrmult.dtype )

[[  6.  20.   7.  20.]
 [ 88.  14. 153.  40.]
 [ 21.  72. 135. 120.]]
float64


In [13]:
#Division of 2 ndarrays
print()
arrdiv = arr1/arr2
print( arrdiv )
print( arrdiv.dtype )


[[ 0.16666667  0.8         7.          5.        ]
 [ 1.375      14.          1.88888889 10.        ]
 [21.          8.          5.4         7.5       ]]
float64


In [14]:
#Division of 2 ndarrays

arrdiv = arr1//arr2
print( arrdiv )
print( arrdiv.dtype )
print(f"len(arrdiv) = { len(arrdiv) }")
print()

[[ 0.  0.  7.  5.]
 [ 1. 14.  1. 10.]
 [21.  8.  5.  7.]]
float64
len(arrdiv) = 3



In [15]:
#Power of 2 ndarrays
arrpow = arr1**arr2
print( arrpow )
print( arrpow.dtype )
print()

[[1.00000000e+00 1.02400000e+03 7.00000000e+00 1.00000000e+02]
 [2.14358881e+08 1.40000000e+01 1.18587876e+11 4.00000000e+02]
 [2.10000000e+01 1.38240000e+04 1.43489070e+07 8.10000000e+05]]
float64



In [17]:
#Square root of 2 ndarrays
print( arr1 )
print()
arrsqrt = arr1**0.5
print( arrsqrt )
print( arrsqrt.dtype)

[[ 1.  4.  7. 10.]
 [11. 14. 17. 20.]
 [21. 24. 27. 30.]]

[[1.         2.         2.64575131 3.16227766]
 [3.31662479 3.74165739 4.12310563 4.47213595]
 [4.58257569 4.89897949 5.19615242 5.47722558]]
float64


In [18]:
print( np.sqrt( arr1 ) )

[[1.         2.         2.64575131 3.16227766]
 [3.31662479 3.74165739 4.12310563 4.47213595]
 [4.58257569 4.89897949 5.19615242 5.47722558]]


In [19]:
print( np.divide( arr1, arr2 ) )

[[ 0.16666667  0.8         7.          5.        ]
 [ 1.375      14.          1.88888889 10.        ]
 [21.          8.          5.4         7.5       ]]


In [20]:
#Exponent of an numpy array

print( np.exp( arr1 ) )

[[2.71828183e+00 5.45981500e+01 1.09663316e+03 2.20264658e+04]
 [5.98741417e+04 1.20260428e+06 2.41549528e+07 4.85165195e+08]
 [1.31881573e+09 2.64891221e+10 5.32048241e+11 1.06864746e+13]]


In [26]:
#Mean of an numpy array
print( arr1 )
print()
print( np.mean( arr1 ) )
print()

row = len( arr1 )
col = len( arr1[0] )
n = row * col

sum = 0

for i in arr1:   #i = [11. 14. 17. 20.]
    for j in i:   #j = 11.
        sum = sum + j

print(f"Total sum of numbers = { sum }")
print(f"Total no. of element = {n}")
print(f"Mean of arr1 = { sum/n }")
print("This is how mean() works in python")

[[ 1.  4.  7. 10.]
 [11. 14. 17. 20.]
 [21. 24. 27. 30.]]

15.5

Total sum of numbers = 186.0
Total no. of element = 12
Mean of arr1 = 15.5
This is how mean() works in python


In [29]:
#Mean of cols of an numpy array

print( np.mean( arr1 , axis = 0) )    #axis = 0, is for the mean()
print()

[11. 14. 17. 20.]



In [30]:
#Sum of rows of an numpy array

print( np.sum( arr1 , axis = 1) )
print()
#Sum of cols of an numpy array

print( np.sum( arr1 , axis = 0) )
print()

[ 22.  62. 102.]

[33. 42. 51. 60.]



In [31]:
#Subtract of rows of an numpy array

print( np.subtract( arr1 , axis = 1) )
print()
#Sum of cols of an numpy array

print( np.subtract( arr1 , axis = 0) )
print()

#Above Program will give Error

ValueError: invalid number of arguments

In [32]:
#Median of rows of an numpy array
print( arr1 )
print()
print( np.median( arr1 , axis = 1) )
print()
#Sum of cols of an numpy array

print( np.median( arr1 , axis = 0) )
print()

[[ 1.  4.  7. 10.]
 [11. 14. 17. 20.]
 [21. 24. 27. 30.]]

[ 5.5 15.5 25.5]

[11. 14. 17. 20.]

