In [2]:
#Introduction program
import numpy as np

In [6]:
#Single Dimension Array
l = [ [1, 12, 0, 4], [13, 2, 10, 5] ]  
print(f"type(l)= {type(l)}" )

#syntax :- np.array( list )
arr = np.array( l )

print(f"l = { l }\n")
print(f"arr = \n{ arr }" )
print(f"type(arr) = { type(arr) }\n")
print(f"type(l) = { type(l) }\n")

type(l)= <class 'list'>
l = [[1, 12, 0, 4], [13, 2, 10, 5]]

arr = 
[[ 1 12  0  4]
 [13  2 10  5]]
type(arr) = <class 'numpy.ndarray'>

type(l) = <class 'list'>



In [4]:
print( f"len(l) = { len(l) }" )
print( f"len(arr) = { len(arr) }" )

print( arr.shape )
print( f"This is Numpy Array = { arr }" )
print( f"This is list = { l }" )

len(l) = 2
len(arr) = 2
(2, 4)
This is Numpy Array = [[ 1 12  0  4]
 [13  2 10  5]]
This is list = [[1, 12, 0, 4], [13, 2, 10, 5]]


In [5]:
arr

array([[ 1, 12,  0,  4],
       [13,  2, 10,  5]])

In [12]:
l = [ [1, 2, 3, 4, 5], [6, 9, 10], [10, 11, 19, 34] ]
print(l)
print()
arr2 = np.array( l )
print()
print( arr2  ) 
print()
print( type(arr2)  ) 
print()
print( arr2.shape )

[[1, 2, 3, 4, 5], [6, 9, 10], [10, 11, 19, 34]]


[list([1, 2, 3, 4, 5]) list([6, 9, 10]) list([10, 11, 19, 34])]

<class 'numpy.ndarray'>

(3,)


c:\users\pc\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  after removing the cwd from sys.path.


In [13]:
a, b = 2, 3
print(f"a  = { a } and b = { b }")

print( arr )
print()
print(f"arr.shape = { arr.shape }")

row, col = arr.shape

print(f"No. of Rows = {row} and No. of Columns = {col}")
print(f"No. of Rows = {type(row)} and No. of Columns = {type(col)}")

a  = 2 and b = 3
[[ 1 12  0  4]
 [13  2 10  5]]

arr.shape = (2, 4)
No. of Rows = 2 and No. of Columns = 4
No. of Rows = <class 'int'> and No. of Columns = <class 'int'>


In [14]:
#Printing the elements of array
count = 1
print(arr)
print()
for i in arr:    #i = [1 12 0 4] -> [8 1 5 0]
    print(f"Row {count} : ", end = '')
    print(i)
    
    for j in i:
        print(f"j = {j}")
    count += 1

print( f"count = { count }" )

[[ 1 12  0  4]
 [13  2 10  5]]

Row 1 : [ 1 12  0  4]
j = 1
j = 12
j = 0
j = 4
Row 2 : [13  2 10  5]
j = 13
j = 2
j = 10
j = 5
count = 3


In [9]:
#Changing the elements of array using indexes( Mutability )
print("old arr :- ")
print(arr)
print()
print( f"arr[0] = { arr[0] }" )
print( f"arr[0][1] = { arr[0][1] }" )
print()

arr[0][2] = 1
arr[1][2] = 2
print("New arr :- ")
print( arr )

old arr :- 
[[ 1 12  0  4]
 [13  2 10  5]]

arr[0] = [ 1 12  0  4]
arr[0][1] = 12

New arr :- 
[[ 1 12  1  4]
 [13  2  2  5]]
