In [1]:
import numpy as np
#DealingWithBooleanValues

In [4]:
arr = np.array( [ list( range(0, 10, 3) ), list( range(10, 20, 3) ), list( range(20, 30, 3) ) ] )
print(arr)

[[ 0  3  6  9]
 [10 13 16 19]
 [20 23 26 29]]


In [6]:
#Method 1 :- 
newarr1 = arr > 13 #greater than 13 true and equal and lessthan 13 false
print( newarr1 )
print()

Following is newarr1,
[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]



In [14]:
#Method 2( Algorithm Based ) :- 
newarr2 = []

for i in arr:     #[0 3 6 9], [ 10 13 16 19 ]
    temp = []
    for j in i:   # 13
        temp.append( j > 13 )   #temp = [False, False, True, True]
    
    newarr2.append( temp )   #[], [ [False, False, False, False], [False, False, True, True], [True, True, True, True] ]
print(temp)
print(newarr2)


[True, True, True, True]
[[False, False, False, False], [False, False, True, True], [True, True, True, True]]
[16 19 20 23 26 29]


In [12]:
#Selecting the value inside array 'arr' elements which are true and satisfies the condition

#Method 1 :-
print( arr )
print()
print( newarr1 )
print()
print(f"arr[ newarr1 ] = {arr[ newarr1 ]}" )
print(f"type( arr[newarr1] ) = { type( arr[newarr1] ) }" )
print()

[[ 0  3  6  9]
 [10 13 16 19]
 [20 23 26 29]]

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]

arr[ newarr1 ] = [16 19 20 23 26 29]
type( arr[newarr1] ) = <class 'numpy.ndarray'>



In [19]:
print( arr )
print()
print( newarr1 )
print()
l = []

print( f"len(arr) = { len(arr) }" )

for i in range( len( arr ) ):   #0, 1, 2
    templist = list( arr[i])  #arr[0] = [0 3 6 9] -> [0, 3, 6, 9]
    
    for j in range( len(templist) ): #0, 1, 2, 3  
        if( newarr1[i][j]):
            l.append( arr[i][j] )
print(l)
print(type(l))
l = np.array(l)
print(f"l = {l},type = {type(l)}")

[[ 0  3  6  9]
 [10 13 16 19]
 [20 23 26 29]]

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]

len(arr) = 3
[16, 19, 20, 23, 26, 29]
<class 'list'>
l = [16 19 20 23 26 29],type = <class 'numpy.ndarray'>


In [20]:
print( arr )
print()
print(f"arr[ arr%2 == 0 ] = {arr[ arr%2 == 0 ]}")

[[ 0  3  6  9]
 [10 13 16 19]
 [20 23 26 29]]

arr[ arr%2 == 0 ] = [ 0  6 10 16 20 26]
