In [1]:
import numpy as np
#Random, Union, Intersection, diffrence, etc

In [8]:
#Sorting

unsorted = np.random.rand( 2, 4 )   #It makes 2 list and put both into an another list
#( n, e ) -> n is number of list and e is number of elements in each list. 
print( unsorted )
unsorted.sort()    #Our nd array is now sorted.
print( unsorted )

[[0.1561251  0.73320727 0.51445822 0.36482781]
 [0.81847583 0.76347511 0.24556241 0.58648981]]
[[0.1561251  0.36482781 0.51445822 0.73320727]
 [0.24556241 0.58648981 0.76347511 0.81847583]]


In [9]:
#unique() - Will remove the duplicates.

arr1 = np.array( [1, 2, 3, 3, 9, 1, 2] )
print( np.unique( arr1 ) )

[1 2 3 9]


In [14]:
#intersection of 2 arrays. -> common values will be print

arr2 = [3, 9, 10, 11, 10, 14]

print( f"arr1 = { arr1 }, type = {type(arr1)}" )
print( f"arr2 = { arr2 }, type = {type(arr2)}" )
print()
print( f"np.intersect1d( arr1, arr2 ) = { np.intersect1d( arr1, arr2 ) }" )
print()
print( f"arr1 = { arr1 }, type = {type(arr1)}" )
print( f"arr2 = { arr2 }, type = {type(arr2)}" )

arr1 = [1 2 3 3 9 1 2], type = <class 'numpy.ndarray'>
arr2 = [3, 9, 10, 11, 10, 14], type = <class 'list'>

np.intersect1d( arr1, arr2 ) = [3 9]

arr1 = [1 2 3 3 9 1 2], type = <class 'numpy.ndarray'>
arr2 = [3, 9, 10, 11, 10, 14], type = <class 'list'>


In [15]:
#Union of 2 arrays. -> joining the two arrays 
arr2 = [3, 9, 10, 11, 10, 14]

print( f"arr1 = { arr1 }" )
print( f"arr2 = { arr2 }" )
print()

print( np.union1d( arr1, arr2 ) )
print()
print( f"arr1 = { arr1 }" )
print( f"arr2 = { arr2 }" )

arr1 = [1 2 3 3 9 1 2]
arr2 = [3, 9, 10, 11, 10, 14]

[ 1  2  3  9 10 11 14]

arr1 = [1 2 3 3 9 1 2]
arr2 = [3, 9, 10, 11, 10, 14]


In [17]:
#diifrence of 2 numpy arrays
print( f"arr1 = { arr1 }" )
print( f"arr2 = { arr2 }" )
print()
print( np.setdiff1d( arr1, arr2 ) ) 
#removes the common part of arr1 and arr2, and then, it shows arr1.
print()
print( f"arr1 = { arr1 }" )
print( f"arr2 = { arr2 }" )
print()
print( np.setdiff1d( arr2, arr1 ) )
#removes the common part of arr1 and arr2, and then, it shows arr2.

arr1 = [1 2 3 3 9 1 2]
arr2 = [3, 9, 10, 11, 10, 14]

[1 2]

arr1 = [1 2 3 3 9 1 2]
arr2 = [3, 9, 10, 11, 10, 14]

[10 11 14]


In [18]:
print( f"arr1 = { arr1 }" )
print()
print( f"arr2 = { arr2 }" )
print()
print( f"np.in1d( arr1, arr2 ) = { np.in1d( arr1, arr2 ) }" )
print()

arr1 = [1 2 3 3 9 1 2]

arr2 = [3, 9, 10, 11, 10, 14]

np.in1d( arr1, arr2 ) = [False False  True  True  True False False]

